In [20]:
from arcgis.gis import GIS
from arcgis.geocoding import geocode
from arcgis.geoenrichment import BufferStudyArea, enrich
from arcgis.geometry import Geometry

gis = GIS(username='gpec447sp26_33')

Enter password:  ········

In [21]:
pt = Geometry({
    "x": 139.8996,
    "y": 36.5595,
    "spatialReference": {"wkid": 4326}
})

In [22]:
travel_area = BufferStudyArea(
    area=pt,
    radii=[5, 10, 15],
    units="Minutes",
    travel_mode="Driving",
    overlap=True
)

In [23]:
result = enrich(
    study_areas=[travel_area],
    data_collections=["KeyGlobalFacts"]
)

result.head()

,source_country,area_type,buffer_units,buffer_units_alias,buffer_radii,aggregation_method,population_to_polygon_size_rating,apportionment_confidence,has_data,totpop,tothh,avghhsz,totfemales,totmales,SHAPE
0,JPN,NetworkServiceArea,Minutes,Drive Time Minutes,5.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,39934.0,21266.0,1.88,19026.0,20903.0,"{""rings"": [[[139.90865104676786, 36.5736942068..."
1,JPN,NetworkServiceArea,Minutes,Drive Time Minutes,10.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,151551.0,75921.0,2.0,74331.0,77218.0,"{""rings"": [[[139.90640526933737, 36.5954782532..."
2,JPN,NetworkServiceArea,Minutes,Drive Time Minutes,15.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,286643.0,136118.0,2.11,142562.0,144073.0,"{""rings"": [[[139.90752815805263, 36.6188343433..."

In [24]:
walk_area = BufferStudyArea(
    area=pt,
    radii=[5, 10, 15],
    units="Minutes",
    travel_mode="Walking",
    overlap=True
)

walk_result = enrich(
    study_areas=[walk_area],
    data_collections=["KeyGlobalFacts"]
)

walk_result.head()

,source_country,area_type,buffer_units,buffer_units_alias,buffer_radii,aggregation_method,population_to_polygon_size_rating,apportionment_confidence,has_data,totpop,tothh,avghhsz,totfemales,totmales,SHAPE
0,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,5.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,1927.0,974.0,1.98,955.0,972.0,"{""rings"": [[[139.90123997980987, 36.5633636282..."
1,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,10.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,8641.0,4971.0,1.74,4027.0,4615.0,"{""rings"": [[[139.90258744644782, 36.5667322947..."
2,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,15.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,19965.0,11202.0,1.78,9327.0,10637.0,"{""rings"": [[[139.9034857581387, 36.57010096220..."

In [25]:
m = gis.map("Utsunomiya, Japan")

walk_result.spatial.plot(
    map_widget=m,
    renderer_type="u",          # unique value renderer
    col="bufferRadii",          # column that separates 5, 10, 15 min areas
    alpha=0.45
)

m

Map(center=[4377278.256872826, 15571651.00303343], extent={'xmin': 15550611.6192735, 'ymin': 4351118.478174847…

In [41]:
from pathlib import Path
import geopandas as gpd

# Find project folder from current notebook location
current_dir = Path.cwd()

# Data folder
data_dir = current_dir / "data"

In [27]:
lrt_stops_path = data_dir / "lrt_stops.shp"

lrt_stops = gpd.read_file(lrt_stops_path)

lrt_stops.head()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,loc_type,plat_code,geometry
0,1_01,None,宇都宮駅東口,None,36.559491,139.899640,1_01,None,0,None,POINT (139.89964 36.55949)
1,10_01,None,清陵高校前,None,36.544896,139.976088,10_01,None,0,None,POINT (139.97609 36.5449)
2,10_02,None,清陵高校前,None,36.544864,139.976095,10_02,None,0,None,POINT (139.97609 36.54486)
3,11_01,None,清原地区市民センター前,None,36.547578,139.984119,11_01,None,0,None,POINT (139.98412 36.54758)
4,12_01,None,グリーンスタジアム前,None,36.554115,139.983072,12_01,None,0,None,POINT (139.98307 36.55411)

In [31]:
shp_files = list(data_dir.glob("lrt_stops.shp"))
shp_files

[PosixPath('/home/miwatanabe/private/UtsunomiyaLRT/data/lrt_stops.shp')]

In [32]:
lrt_stops_path = shp_files[0]   # change index if needed
lrt_stops = gpd.read_file(lrt_stops_path)

lrt_stops.head()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,loc_type,plat_code,geometry
0,1_01,None,宇都宮駅東口,None,36.559491,139.899640,1_01,None,0,None,POINT (139.89964 36.55949)
1,10_01,None,清陵高校前,None,36.544896,139.976088,10_01,None,0,None,POINT (139.97609 36.5449)
2,10_02,None,清陵高校前,None,36.544864,139.976095,10_02,None,0,None,POINT (139.97609 36.54486)
3,11_01,None,清原地区市民センター前,None,36.547578,139.984119,11_01,None,0,None,POINT (139.98412 36.54758)
4,12_01,None,グリーンスタジアム前,None,36.554115,139.983072,12_01,None,0,None,POINT (139.98307 36.55411)

In [33]:
from arcgis.geometry import Geometry
from arcgis.geoenrichment import BufferStudyArea

study_areas = []

# Make sure lrt_stops is in WGS84 for ArcGIS API
lrt_stops_wgs84 = lrt_stops.to_crs(epsg=4326)

for idx, row in lrt_stops_wgs84.iterrows():
    pt = Geometry({
        "x": row.geometry.x,
        "y": row.geometry.y,
        "spatialReference": {"wkid": 4326}
    })

    area = BufferStudyArea(
        area=pt,
        radii=[5, 10, 15],
        units="Minutes",
        travel_mode="Walking",
        overlap=True
    )

    study_areas.append(area)

In [34]:
from arcgis.geoenrichment import enrich

walk_results = enrich(
    study_areas=study_areas,
    data_collections=["KeyGlobalFacts"]
)

walk_results.head()

,source_country,area_type,buffer_units,buffer_units_alias,buffer_radii,aggregation_method,population_to_polygon_size_rating,apportionment_confidence,has_data,totpop,tothh,avghhsz,totfemales,totmales,SHAPE
0,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,5.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,1927.0,974.0,1.98,955.0,972.0,"{""rings"": [[[139.90123997980987, 36.5633636282..."
1,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,10.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,8641.0,4971.0,1.74,4027.0,4615.0,"{""rings"": [[[139.90258744644782, 36.5667322947..."
2,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,15.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,19965.0,11202.0,1.78,9327.0,10637.0,"{""rings"": [[[139.9034857581387, 36.57010096220..."
3,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,5.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,89.0,50.0,1.78,42.0,49.0,"{""rings"": [[[139.97512607416212, 36.5483169163..."
4,JPN,NetworkServiceArea,Minutes,Walk Time Minutes,10.0,BlockApportionment:JP.Blocks;PointsLayer:JP.Bl...,-1.0,-1.0,1,792.0,275.0,2.88,411.0,381.0,"{""rings"": [[[139.97377860662587, 36.5521347392..."

Here it shows areas that are farther from the LRT stop in different travel times (5 min, 10 min, 15 min).

In [40]:
m = gis.map("Utsunomiya, Japan")

walk_results.spatial.plot(
    map_widget=m,
    renderer_type="c",          # class breaks / graduated colors
    col="buffer_radii",          # column for 5, 10, 15 minute areas
    class_count=3,
    alpha=0.45,
    legend=True
)

m

Map(center=[4377278.256872826, 15571651.00303343], extent={'xmin': 15550611.6192735, 'ymin': 4351118.478174847…

In [43]:
m = gis.map("Utsunomiya, Japan")

result.spatial.plot(
    map_widget=m,
    renderer_type="c",          # class breaks / graduated colors
    col="buffer_radii",          # column for 5, 10, 15 minute areas
    class_count=3,
    alpha=0.45,
    legend=True
)

m

Map(center=[4377278.256872826, 15571651.00303343], extent={'xmin': 15550611.6192735, 'ymin': 4351118.478174847…